"""tests/_golden_detector.py — a STABLE detector + resolver for the CP4 Slice B canonical goldens.

The resolved-profile digest is the blake2b of the module file that DEFINES the detector class
(``gate.detector_registry.content_address`` → ``inspect.getfile``). So any golden that pins a subject /
result-ref / signature transitively depends on THIS file's bytes. Keeping the golden detector in its own
minimal module — rather than reusing a churning ``test_*.py`` helper — means unrelated test edits do NOT
rebake the pinned constants. DO NOT edit this file casually: a change here re-bakes every golden digest
that depends on it (the golden tests will fail and must be re-pinned deliberately). TEST-ONLY (excluded
from the shipped wheel).
"""
from __future__ import annotations

from core import Command, Fixtures, Verdict
from engine.calibration import ResolvedDetector
from gate.detector_registry import profile_of


class GoldenScriptedDetector:
    """A detector whose per-fixture verdicts follow a fixed script (call order), so a golden run is
    deterministic. The verdicts are supplied by the golden test; the class SOURCE is what content-addresses
    into the profile digest, and it is intentionally frozen."""

    def __init__(self, verdicts: list[Verdict]) -> None:
        self.fixtures = Fixtures()
        self._verdicts = verdicts
        self._i = 0

    def entrypoint(self) -> Command:
        return Command(argv=("true",))

    def assert_invariant(self, result: object) -> Verdict:
        v = self._verdicts[self._i]
        self._i += 1
        return v


def golden_resolver(detector: GoldenScriptedDetector):  # type: ignore[no-untyped-def]
    """A ``BundleResolver`` over the golden detector — the atomic (assertion + profile digest + frozen
    command) bundle both the calibration and re-calibration paths consume."""
    return lambda _id: ResolvedDetector(
        assertion=detector,
        profile_digest=profile_of(_id, detector).digest(),
        command=detector.entrypoint(),
    )
